Repository eddyspaghette/TreasureFind, pull requests merged in 2022-08, with the labels that each got.

#85 fix null upload && fix maps
  app/src/main/java/com/AERYZ/treasurefind/main/ui/hider_place/HiderPlaceFragment.kt
  app/src/main/java/com/AERYZ/treasurefind/main/ui/hider_place/HiderPlaceViewModel.kt
  app/src/main/res/layout/activity_maps.xml
Labels: bug, Very Important

#120 change showing sid to sr's author name
  app/src/main/java/com/AERYZ/treasurefind/main/ui/hider_map/SrFragment.kt
  app/src/main/res/layout/fragment_sr.xml
Labels: enhancement, Very Important

#128 add loading image button to sr activity
  app/src/main/java/com/AERYZ/treasurefind/main/ui/seeker_map/SeekerSubmitFragment.kt
  app/src/main/res/layout/fragment_seeker_submit.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#127 add swipe gesture to validating fragment
  app/src/main/java/com/AERYZ/treasurefind/main/OnSwipeTouchListener.kt
  app/src/main/java/com/AERYZ/treasurefind/main/entry_point/MainActivity.kt
  app/src/main/java/com/AERYZ/treasurefind/main/ui/hider_map/HiderValidateFragment.kt
  app/src/main/res/layout/fragment_hider_validate.xml
Labels: enhancement

#143 Change marker icon
  app/src/main/java/com/AERYZ/treasurefind/main/ui/hider_map/HiderMapActivity.kt
  app/src/main/java/com/AERYZ/treasurefind/main/ui/seeker_map/SeekerMapActivity.kt
  app/src/main/res/drawable/marker_seeker.png
  app/src/main/res/drawable/marker_treasure.png
  app/src/main/res/drawable/marker_treasuretwo.png
Labels: enhancement

#150 implement distance on feed and sorted by closest distance
  app/src/main/java/com/AERYZ/treasurefind/db/MyFirebase.kt
  app/src/main/java/com/AERYZ/treasurefind/main/ui/feed/FeedFragment.kt
  app/src/main/java/com/AERYZ/treasurefind/main/ui/feed/FeedListViewAdapter.kt
  app/src/main/java/com/AERYZ/treasurefind/main/ui/feed/FeedViewModel.kt
  app/src/main/java/com/AERYZ/treasurefind/main/util/Util.kt
  app/src/main/res/drawable/ic_feed_distance_marker.xml
  app/src/main/res/layout/fragment_feed_listitem.xml
Labels: enhancement

#154 fixed distance icon on feedpage
  app/src/main/res/layout/fragment_feed_listitem.xml
Labels: bug
